const $ = (s, root=document)=>root.querySelector(s);
const icons={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',activities:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',saved:'<path d="M6 3h12v18l-6-4-6 4Z"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',back:'<path d="m15 5-7 7 7 7"/>',send:'<path d="M12 19V5m-6 6 6-6 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="currentColor"/><circle cx="16" cy="17" r="3" fill="currentColor"/>',moon:'<path d="M20 14A9 9 0 0 1 10 4a9 9 0 1 0 10 10Z"/>',play:'<path d="m9 5 11 7-11 7Z" fill="currentColor" stroke="none"/>',pause:'<path d="M8 5v14M16 5v14" stroke-width="4"/>',check:'<path d="m5 12 4 4L19 6"/>',leaf:'<path d="M20 3C5 2 2 10 6 16s15 2 14-13Z"/><path d="m4 21 11-12"/>',chat:'<path d="M21 11a8 8 0 0 1-8 8H5l-3 3V11a9 9 0 0 1 19 0Z"/>',chevron:'<path d="m9 5 7 7-7 7"/>',signal:'<path d="M4 18v-3m5 3v-6m5 6V9m5 9V5"/>',battery:'<rect x="2" y="6" width="18" height="12" rx="3"/><path d="M22 10v4M5 9h12v6H5Z" fill="currentColor"/>'};
function icon(name){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[name]||icons.moon)+'</svg>'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const key='evening-lounge-demo-v1';let store={books:[],notes:[],chats:[],style:'Gentle',reduced:false};try{const d=JSON.parse(localStorage.getItem(key));if(d&&Array.isArray(d.chats))store={...store,...(window.CaveState?CaveState.normalize(d):d)};}catch{}if(!['Gentle','Reflective','Practical'].includes(store.style))store.style='Gentle';
store.profile=store.profile||null;store.worlds=Array.isArray(store.worlds)?store.worlds:[];store.activeWorld=store.activeWorld||null;store.loggedIn=!!store.loggedIn;
store.selectedCompanion=store.selectedCompanion||store.worlds.find(w=>w.id===store.activeWorld)?.companion||'maya';store.connectionRole=store.connectionRole||'Reflection partner';store.presence=store.presence||'alone';store.worlds.forEach(w=>{w.vibe=['Cozy','Fresh','Futuristic','Calm'].includes(w.vibe)?w.vibe:'Calm';w.prompt=w.prompt||''});
store.worlds.forEach(w=>{w.companion=w.companion||store.selectedCompanion;w.presence=w.presence||store.presence;w.style=w.style||store.style;});
function restoreRoomCompany(){const w=store.worlds.find(w=>w.id===store.activeWorld);if(w){store.selectedCompanion=w.companion||'maya';store.presence=w.presence||'alone';store.style=w.style||'Gentle';}}
restoreRoomCompany();
function finishBeforeRoomChange(){if(messages.length||draft.trim()){go('finish');toast('Finish or save this conversation before changing rooms.');return true}return false}
let screen='welcome',messages=[],currentId=null,deletePending=false,medTimer=null,seconds=180,playing=false,gameTimeouts=[],sequence=[],guess=0,gameReady=false,gameLevel=1;
function persist(){try{localStorage.setItem(key,JSON.stringify(store));return true}catch{toast('Storage unavailable. Your changes cannot be saved.');return false}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
store.notes=Array.isArray(store.notes)?store.notes:[];let noteDraft='',noteTitle='',openedNote=null,noteReturn='saved',musicReturn='room',notesFilter='room',activityReturn='room',meditationReturn='room';

store.books=Array.isArray(store.books)?store.books:[];
let readingId=null,bookDelete=false,moodChoice=null,moodReturn='home',booksFilter='room',importDraft=null,readerBookmarks=false;
store.books.forEach(b=>{b.roomIds=Array.isArray(b.roomIds)?b.roomIds:[store.activeWorld||store.worlds[0]?.id].filter(Boolean);b.bookmarks=Array.isArray(b.bookmarks)?b.bookmarks:[];b.theme=b.theme||'cream';b.font=b.font||18;b.pages=b.pages?.length?b.pages:paginate(b.text||'');b.page=Math.max(0,Math.min(b.page||0,b.pages.length-1));});
const moodOptions={stressed:{label:'Stressed',title:'Try a softer atmosphere',description:'Warm light, gentle amber tones and Warm stillness at 25%. Your mute setting stays as it is.',track:'warm',volume:.25},low:{label:'Low',title:'Try a little more light',description:'A brighter golden glow and Floating light at 35%. Your mute setting stays as it is.',track:'float',volume:.35},restless:{label:'Restless',title:'Try a quieter atmosphere',description:'Muted blue tones and Deep calm at 25%. Your motion preference stays as it is.',track:'deep',volume:.25},okay:{label:'Okay',title:'Try an open, balanced atmosphere',description:'A light neutral glow and Floating light at 40%. Your mute setting stays as it is.',track:'float',volume:.4}};
function readingBook(){return store.books.find(b=>b.id===readingId)}
function paginate(text){const pages=[];let start=0;while(start<text.length){let end=Math.min(start+1100,text.length);if(end<text.length){const gap=text.lastIndexOf(' ',end);if(gap>start+700)end=gap+1}pages.push(text.slice(start,end));start=end}return pages}
function addBook(title,text,sample=false){const book={id:'book-'+Date.now(),title,text,pages:paginate(text),page:0,font:18,theme:'cream',roomIds:[activeWorld().id].filter(Boolean),bookmarks:[],sample,created:new Date().toISOString(),lastRead:Date.now()};store.books.unshift(book);if(persist()){readingId=book.id;importDraft=null;go('reader');toast('Book saved in your library and this room.')}else store.books.shift()}
function shelfBooks(){return store.books.filter(b=>b.roomIds.includes(activeWorld().id))}
function recentBook(books=shelfBooks()){return [...books].sort((a,b)=>(b.lastRead||0)-(a.lastRead||0))[0]}
function bookCover(b,small=false){return '<span class="book-cover typographic-cover '+(small?'small-cover':'')+'" aria-hidden="true"><span class="cover-rule"></span><strong>'+esc(b.title)+'</strong><span class="cover-star">✦</span><small>'+(b.sample?'CAVE ORIGINAL':'PERSONAL LIBRARY')+'</small></span>'}
function bookProgress(b){return 'Section '+(b.page+1)+' of '+b.pages.length+' · '+Math.round((b.page+1)/b.pages.length*100)+'%'}
function roomShelf(){const books=shelfBooks(),b=recentBook();return '<div class="room-bookshelf"><button class="shelf-label" data-action="books"><span>Your bookshelf</span><span>'+books.length+' '+(books.length===1?'book':'books')+' →</span></button>'+(b?'<button class="shelf-resume" data-book="'+esc(b.id)+'">'+bookCover(b,true)+'<span><small>CONTINUE READING</small><strong>'+esc(b.title)+'</strong><span>'+bookProgress(b)+'</span></span></button>':'<button class="shelf-empty" data-action="books">Bring a book into your room <span>＋</span></button>')+'</div>'}
function booksView(){const books=booksFilter==='all'?store.books:shelfBooks(),recent=recentBook(books);return header('Bookshelf','room')+'<p class="overline">'+esc(activeWorld().name)+'</p><h1 class="title">Stories to settle into.</h1><div class="note-filters" role="group" aria-label="Filter books"><button data-books-filter="room" aria-pressed="'+(booksFilter==='room')+'">This room</button><button data-books-filter="all" aria-pressed="'+(booksFilter==='all')+'">All books</button></div>'+button('Add a book','add-book','primary')+(recent?'<button class="continue-book" data-book="'+esc(recent.id)+'">'+bookCover(recent,true)+'<span><small>CONTINUE READING</small><strong>'+esc(recent.title)+'</strong><span>'+bookProgress(recent)+'</span><b>Continue →</b></span></button>':'<div class="notebook-empty"><p class="card-title">A shelf of your own.</p><p class="card-sub">'+(booksFilter==='room'?'Choose a book from your library or import something new.':'Import a text book to begin.')+'</p></div>')+'<div class="books-grid">'+books.map(b=>'<div class="shelf-book"><button data-book="'+esc(b.id)+'" aria-label="Read '+esc(b.title)+'">'+bookCover(b)+'<strong>'+esc(b.title)+'</strong><small>'+bookProgress(b)+'</small></button><button class="text-button" data-book-manage="'+esc(b.id)+'">Manage book</button></div>').join('')+'</div><p class="disclosure">Books, bookmarks and reading position are saved only in this browser. No cloud backup or cross-device sync.</p>';}
function readerView(){const b=readingBook(),marked=b.bookmarks.some(m=>m.page===b.page);return header('Reading room','books')+'<p class="overline">'+esc(activeWorld().name)+'</p><h1 class="reader-title">'+esc(b.title)+'</h1><div class="reader-tools"><button class="text-button" data-book-font="-2" aria-label="Smaller text" '+(b.font<=16?'disabled':'')+'>A−</button><span>'+bookProgress(b)+'</span><button class="text-button" data-book-font="2" aria-label="Larger text" '+(b.font>=26?'disabled':'')+'>A+</button></div><div class="reader-themes" role="group" aria-label="Reading theme">'+['cream','light','dark'].map(t=>'<button data-reader-theme="'+t+'" aria-pressed="'+(b.theme===t)+'">'+t[0].toUpperCase()+t.slice(1)+'</button>').join('')+'</div><article class="reading-page theme-'+b.theme+'" style="font-size:'+b.font+'px">'+esc(b.pages[b.page])+'</article><div class="reader-pagination"><button class="secondary" data-book-page="-1" '+(b.page===0?'disabled':'')+'>Previous</button><button class="secondary" data-book-page="1" '+(b.page===b.pages.length-1?'disabled':'')+'>Next</button></div><div class="reader-mark-actions">'+button(marked?'Remove bookmark':'Bookmark this section','toggle-bookmark','secondary')+button('Bookmarks ('+b.bookmarks.length+')','show-bookmarks','tertiary')+'</div>'+(readerBookmarks?'<div class="bookmark-list"><h2>Saved places</h2>'+(b.bookmarks.length?b.bookmarks.map(m=>'<div class="bookmark-row"><button data-bookmark-jump="'+m.page+'"><strong>Section '+(m.page+1)+'</strong><span>'+esc(b.pages[m.page]?.slice(0,100)||'Saved place')+'…</span></button><button class="text-button" data-bookmark-remove="'+m.page+'" aria-label="Remove bookmark at section '+(m.page+1)+'">×</button></div>').join(''):'<p class="card-sub">Mark a section to return to it later.</p>')+'</div>':'')+'<p class="disclosure">Your place is saved automatically in this browser. Text sections stay fixed when you change font size.</p>';}
function manageBookView(){const b=readingBook();return header('Manage book','books')+'<div class="book-manage-cover">'+bookCover(b)+'</div><h1 class="reader-title">'+esc(b.title)+'</h1><p class="card-sub">One book, one reading position, across all your rooms.</p><p class="section-label">On these room shelves</p>'+store.worlds.map(w=>'<button class="option room-book-toggle" data-book-room="'+esc(w.id)+'" aria-pressed="'+b.roomIds.includes(w.id)+'"><span>'+esc(w.name)+'</span><span>'+(b.roomIds.includes(w.id)?'✓ Added':'＋ Add')+'</span></button>').join('')+'<p class="disclosure">Removing from a room keeps the book, progress and bookmarks in All books.</p><button class="primary" data-book="'+esc(b.id)+'">Continue reading</button>'+(bookDelete?'<div class="card"><p>Delete this book from your entire library and every room? Its reading position and bookmarks will also be deleted.</p>'+button('Delete everywhere','delete-book','secondary danger')+button('Keep book','keep-book','tertiary')+'</div>':button('Delete from library','ask-delete-book','tertiary danger'));}

function moodSnapshot(){return {mood:store.mood||null,musicTrack:store.musicTrack||'warm',musicVolume:store.musicVolume??.6}}
function applyMood(){if(!moodOptions[moodChoice])return;const old={...store},before=moodSnapshot();if(!store.moodOriginal)store.moodOriginal=before;store.moodUndo=before;store.mood=moodChoice;store.musicTrack=moodOptions[moodChoice].track;store.musicVolume=moodOptions[moodChoice].volume;if(persist()){window.ambientMusic?.changeTrack();go(moodReturn);toast('Atmosphere changed. You can undo it anytime.')}else store=old}
function restoreMood(original=false){const target=original?store.moodOriginal:store.moodUndo;if(!target)return;const old={...store};Object.assign(store,target);store.moodUndo=null;if(original)store.moodOriginal=null;if(persist()){window.ambientMusic?.changeTrack();render();toast('Previous atmosphere restored.')}else store=old}

const noteDrafts={};let draft='',worldReturn='home',editingWorld=null,worldDraft=null;
const companions=[{id:'maya',name:'Maya',initial:'M',about:'Woman · 38 · South Asian',color:'#B9ADEA'},{id:'leo',name:'Leo',initial:'L',about:'Man · 29 · Black',color:'#E6B77A'},{id:'alex',name:'Alex',initial:'A',about:'Nonbinary · 56 · East Asian',color:'#A8C7BC'}];
let caveScroll={x:120,y:90},caveZoom=1,caveZoomFrame=0;
function caveBaseWidth(){return Math.max(1020,Math.ceil(store.worlds.length/3)*230+300)}
function moveCaveCloser(clientX,clientY,reset=false){const v=$('.cave-viewport'),p=$('.cave-panorama');if(!v||!p)return;cancelAnimationFrame(caveZoomFrame);const rect=v.getBoundingClientRect(),px=clientX==null?v.clientWidth/2:clientX-rect.left,py=clientY==null?v.clientHeight/2:clientY-rect.top,from=caveZoom,to=reset?1:Math.min(1.8,Math.round((caveZoom+.4)*10)/10),wx=(v.scrollLeft+px)/from,wy=(v.scrollTop+py)/from,start=performance.now(),reduced=store.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;function frame(now){if(!v.isConnected)return;const t=reduced?1:Math.min(1,(now-start)/480),ease=1-Math.pow(1-t,3);caveZoom=from+(to-from)*ease;p.style.width=caveBaseWidth()*caveZoom+'px';p.style.height=660*caveZoom+'px';v.scrollLeft=wx*caveZoom-px;v.scrollTop=wy*caveZoom-py;caveScroll={x:v.scrollLeft,y:v.scrollTop};if(t<1)caveZoomFrame=requestAnimationFrame(frame);else{$('[data-cave-zoom="reset"]').disabled=caveZoom<=1;$('[data-cave-zoom="closer"]').disabled=caveZoom>=1.8;$('.cave-depth-label').textContent=Math.round(caveZoom*100)+'% · 2D exploration preview'}}caveZoomFrame=requestAnimationFrame(frame)}
function initCaveMap(){const v=$('.cave-viewport');v.scrollLeft=caveScroll.x;v.scrollTop=caveScroll.y;v.addEventListener('scroll',()=>{caveScroll={x:v.scrollLeft,y:v.scrollTop}});let drag=null,suppress=false,lastTap=null,touchStart=null;v.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'){touchStart={x:e.clientX,y:e.clientY,time:performance.now()};return}if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,left:v.scrollLeft,top:v.scrollTop,id:e.pointerId,moved:false};suppress=false});v.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>6){drag.moved=true;v.setPointerCapture(drag.id);v.classList.add('dragging');v.scrollLeft=drag.left-dx;v.scrollTop=drag.top-dy}});const finish=()=>{if(drag)suppress=drag.moved;drag=null;v.classList.remove('dragging')};v.addEventListener('pointerup',e=>{finish();if(e.pointerType==='mouse'||e.target.closest('button'))return;const now=performance.now();if(touchStart&&now-touchStart.time<300&&Math.hypot(e.clientX-touchStart.x,e.clientY-touchStart.y)<12){if(lastTap&&now-lastTap.time<350&&Math.hypot(e.clientX-lastTap.x,e.clientY-lastTap.y)<30){moveCaveCloser(e.clientX,e.clientY);lastTap=null}else lastTap={x:e.clientX,y:e.clientY,time:now}}else lastTap=null;touchStart=null});v.addEventListener('pointercancel',()=>{finish();touchStart=null;lastTap=null});v.addEventListener('pointerleave',()=>{if(drag&&!drag.moved)finish()});v.addEventListener('click',e=>{if(suppress){e.preventDefault();e.stopPropagation();suppress=false}},true);v.addEventListener('dblclick',e=>{if(e.target.closest('button'))return;e.preventDefault();moveCaveCloser(e.clientX,e.clientY)})}

let comparisonRoom='grotto',comparisonCompany='none';
const environments={grotto:'Sunlit Grotto',hearth:'Hearth Room',lounge:'Evening lounge',forest:'Forest sanctuary',ocean:'Ocean hideaway'};
function activeWorld(){return store.worlds.find(w=>w.id===store.activeWorld)||store.worlds[0]||{name:'Evening lounge',environment:'lounge',mood:'Calm',vibe:'Cozy',companion:'maya',role:'Reflection partner'}}
function companion(id=store.selectedCompanion){return companions.find(c=>c.id===(typeof id==='string'?id:store.selectedCompanion))||companions[0]}
const APP_ASSETS={illustrated:{maya:'companion-maya.png',leo:'companion-leo.png',alex:'companion-alex.png'},interior:'cave-interior.png',cave:'cave-entrance.png',worlds:{grotto:'world-grotto.png',hearth:'world-hearth.png',lounge:'world-lounge.png',forest:'world-forest.png',ocean:'world-ocean.png'},companions:{maya:'companion-maya-realistic.png',leo:'companion-leo-realistic.png',alex:'companion-alex-realistic.png'}};
function portrait(id,w=activeWorld()){return ['grotto','hearth'].includes(w.environment)?APP_ASSETS.companions[id]:APP_ASSETS.illustrated[id]}
function worldVisual(w=activeWorld(),compact=false,id=store.selectedCompanion){const c=companion(id);const showCharacter=id!=='none';return '<div class="world-visual world-'+esc(w.environment)+' vibe-'+esc((w.vibe||'Cozy').toLowerCase())+(compact?' compact':'')+(w.vibe==='Futuristic'?' futuristic':'')+'" aria-label="'+esc(environments[w.environment])+'"><img class="scene-background" src="'+APP_ASSETS.worlds[w.environment]+'" alt="'+esc(environments[w.environment])+'"><div class="world-atmosphere"></div>'+(showCharacter?'<img class="scene-character" data-character="'+c.id+'" src="'+portrait(c.id,typeof w==='undefined'?activeWorld():w)+'" alt="'+c.name+', fictional AI companion">':'')+'<span class="world-mood">'+esc(w.vibe||'Cozy')+'</span>'+(showCharacter?'<div class="world-companion" style="--avatar:'+c.color+'"><img class="badge-portrait" src="'+portrait(c.id,typeof w==='undefined'?activeWorld():w)+'" alt=""><div><strong>'+c.name+'</strong><small>AI companion</small></div></div>':'')+'</div>'}

let custom=null,customTab='space',onboarding=false;
function openCustomize(tab='space',first=false){worldReturn=screen==='chat'?'chat':screen==='room'?'room':screen==='settings'?'settings':'home';custom={worlds:store.worlds.map(w=>({...w})),activeWorld:store.activeWorld,selectedCompanion:store.selectedCompanion,style:store.style,connectionRole:store.connectionRole,presence:store.presence};if(!custom.worlds.length){const w={id:'world-'+Date.now(),name:'My cozy nook',environment:'lounge',vibe:'Cozy',prompt:''};custom.worlds.push(w);custom.activeWorld=w.id}customTab=tab;onboarding=first;go('customize')}
function draftWorld(){return custom.worlds.find(w=>w.id===custom.activeWorld)||custom.worlds[0]}
function captureWorld(){const n=$('#world-name');if(n&&custom){draftWorld().name=n.value.trim()||'My quiet room';draftWorld().prompt=$('#room-prompt')?.value.trim()||''}}
function choiceGroup(label,field,values){const w=draftWorld();return '<p class="section-label">'+label+'</p><div class="option-grid">'+values.map(v=>'<button class="option '+(w[field]===v?'selected':'')+'" data-world-field="'+field+'" data-value="'+esc(v)+'" aria-pressed="'+(w[field]===v)+'">'+esc(field==='environment'?environments[v]:v)+'</button>').join('')+'</div>'}
function applyCustom(fresh=false){if(custom.activeWorld!==store.activeWorld&&finishBeforeRoomChange())return;const room=draftWorld();room.companion=custom.selectedCompanion;room.presence=custom.presence;room.style=custom.style;const old={...store};const oldMessages=messages,oldDraft=draft;store={...store,...custom,sessionClosed:false};if(fresh){store.chats=[{id:Date.now().toString(36),created:new Date().toISOString(),title:'Evening reflection',takeaway:'',worldName:(old.worlds.find(w=>w.id===old.activeWorld)||{}).name,companionName:companion(old.selectedCompanion).name,unsentDraft:draft,messages:messages.map(m=>({...m}))},...old.chats]};if(!persist()){store=old;messages=oldMessages;draft=oldDraft;return}if(fresh){messages=[];draft=''}custom=null;if(fresh&&worldReturn==='chat'&&store.presence==='talk')beginChat();else go(onboarding?'room':worldReturn==='chat'&&store.presence!=='talk'?'room':worldReturn);onboarding=false;toast('Your room is ready.')}

function go(next){if(screen==='notebook'){noteDraft=$('#note-body')?.value||'';noteTitle=$('#note-title')?.value||'';noteDrafts[activeWorld().id]={text:noteDraft,title:noteTitle};}const input=$('#chat-input');if(input)draft=input.value;clearInterval(medTimer);medTimer=null;playing=false;gameTimeouts.forEach(clearTimeout);gameTimeouts=[];gameReady=false;screen=next;if(['room-notes','notebook'].includes(next)){const nd=noteDrafts[activeWorld().id]||{};noteDraft=nd.text||'';noteTitle=nd.title||''}deletePending=false;render();if(next==='chat')$('#chat-input').value=draft;const heading=$('.screen h1, .screen h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true})}}
function header(title,back='home',right=''){return '<div class="header"><button class="icon-button" data-go="'+back+'" aria-label="Back">'+icon('back')+'</button><h2>'+title+'</h2>'+(right||'<span style="width:42px"></span>')+'</div>'}
function art(cls=''){return '<img class="hero-art '+cls+'" src="lounge.png" alt="A warmly lit evening room with a seated illustrated AI companion">'}
function button(label,action,cls='primary',sym=''){return '<button class="'+cls+'" data-action="'+action+'">'+esc(label)+(sym?icon(sym):'')+'</button>'}
function nav(){return '<nav class="nav" aria-label="Main navigation">'+['home','saved','settings'].map(n=>'<button data-go="'+n+'" class="'+(screen===n?'active':'')+'" '+(screen===n?'aria-current="page"':'')+'>'+icon(n)+'<span>'+(n==='home'?'My Cave':n[0].toUpperCase()+n.slice(1))+'</span></button>').join('')+'</nav>'}
function beginChat(){if(messages.length){go('chat');return}draft='';messages=[{role:'ai',speakerName:companion().name,worldName:activeWorld().name,text:'Hi, take a moment to settle in. What’s on your mind this evening?'}];go('chat')}
function render(){const focused=document.activeElement;const focusAttr=focused?.dataset?Object.keys(focused.dataset).find(k=>['customTab','worldField','companion','style','presence','booksFilter','readerTheme'].includes(k)):null;const focusValue=focusAttr?focused.dataset[focusAttr]:null;const focusChoice=focused?.dataset?.value;const detailsOpen=$('details')?.open;let content='',cls='';document.title=screen[0].toUpperCase()+screen.slice(1)+' · The Cave';
if(screen==='welcome'){cls='welcome';content='<div class="brand"><span>◇</span> The Cave</div><div class="cave-welcome"><img src="'+APP_ASSETS.cave+'" alt="A secret cave entrance in a quiet, misty forest, with a warm glow inside"></div><p class="eyebrow">A WORLD THAT FEELS LIKE YOU</p><h1 class="title">A cave of<br>possibilities.</h1><p class="subtitle">Create rooms within your own hidden world.<br>Bring a companion. Or simply be.</p>'+button('Enter my cave','enter','primary','arrow')+'<p class="disclosure">Interactive concept · curated room previews<br>Fictional companions · sample replies · saved locally</p>'}
if(screen==='login'){content=header('Your local demo profile','welcome')+'<p class="overline">WELCOME TO YOUR WORLD</p><h1 class="title">Make a little<br>space for you.</h1><p class="subtitle">Create a profile to build your space and choose who you’d like to talk with.</p><label class="field-label" for="profile-name">What should we call you?</label><input class="input" id="profile-name" maxlength="40" autocomplete="nickname" value="'+esc(store.profile?.name||'')+'" placeholder="Your name"><p class="disclosure">Demo login only. No password, real authentication, or cloud account. Your profile and worlds stay in this browser.</p>'+button(store.profile?'Log in to demo':'Create demo profile','login')}
if(screen==='customize'){const w=draftWorld();content='<div class="header"><button class="text-button" data-action="cancel-custom">Cancel</button><h2>'+(customTab==='companion'?'Choose your company':'Room designer')+'</h2><span></span></div>';
if(customTab==='companion'){content+='<p class="overline">YOUR ROOM, YOUR PACE</p><h1 class="title">How would you<br>like to be here?</h1><div class="presence-options">'+[['alone','Just me','Your room, without a character.'],['quiet','Quiet company','A companion, without conversation.'],['talk','Talk together','Open your conversation when ready.']].map(([id,label,desc])=>'<button class="card choice '+(custom.presence===id?'selected':'')+'" data-presence="'+id+'" aria-pressed="'+(custom.presence===id)+'"><span class="card-content"><strong>'+label+'</strong><span class="card-sub">'+desc+'</span></span><span class="radio"></span></button>').join('')+'</div>'+(custom.presence!=='alone'?'<p class="section-label">Your companion</p>'+companions.map(c=>'<button class="card choice '+(custom.selectedCompanion===c.id?'selected':'')+'" data-companion="'+c.id+'" aria-pressed="'+(custom.selectedCompanion===c.id)+'"><span class="avatar"><img src="'+portrait(c.id,typeof w==='undefined'?activeWorld():w)+'" alt=""></span><span class="card-content"><strong>'+c.name+'</strong><span class="card-sub">'+c.about+'</span></span><span class="radio"></span></button>').join('')+'<p class="section-label">Conversation style</p><div class="option-grid">'+['Gentle','Reflective','Practical'].map(v=>'<button class="option '+(custom.style===v?'selected':'')+'" data-style="'+v+'">'+v+'</button>').join('')+'</div>':'')+button('Apply company','apply-custom')+'<p class="disclosure">Fictional AI characters, not human therapists.</p>';
}else{content+='<p class="overline">CARVE OUT SOMETHING PERSONAL</p><h1 class="title">Imagine your room.</h1><label class="field-label" for="room-prompt">What would you like inside?</label><textarea id="room-prompt" maxlength="600" placeholder="A cozy stone room with a fireplace, books and warm amber light…">'+esc(w.prompt||'')+'</textarea><p class="section-label">Start with a feeling</p><div class="option-grid">'+['Cozy','Fresh','Futuristic','Calm'].map(v=>'<button class="option '+(w.vibe===v?'selected':'')+'" data-room-style="'+v+'" aria-pressed="'+(w.vibe===v)+'">'+v+'</button>').join('')+'</div>'+button('Preview this idea','preview-room','secondary')+'<p class="disclosure">Curated demo: prompts select a matching preset. Individual objects and custom layouts are not generated.</p><div class="designer-preview">'+worldVisual(w,true,'none')+'<span class="preview-caption">'+esc(w.vibe)+' preset'+(w.vibe==='Futuristic'?' · tinted seaside concept':'')+'</span></div><label class="field-label" for="world-name">Room name</label><input class="input" id="world-name" maxlength="45" value="'+esc(w.name)+'"><p class="card-sub refine-hint">Refine your prompt above and preview again. Nothing changes until you save.</p>'+button(onboarding?'Create room & enter':'Save room','apply-custom')+(w.previous?button('Restore previous design','restore-room','tertiary'):'');}}
if(screen==='switch-companion'){content=header('Change companion','customize')+'<h1 class="title">A new companion.<br>Your choice.</h1><p class="subtitle">Your current conversation is still open. Choose what the new companion can see.</p>'+button('Continue with this transcript','switch-continue')+button('Save previous & start fresh','switch-fresh','secondary')+button('Cancel','switch-cancel','tertiary')+'<p class="disclosure">Saved conversations stay in this browser only. Any unsent text is saved separately as an unsent draft.</p>';}
if(screen==='home'){cls='cave-hub';content='<div class="header"><div><p class="overline">YOUR OWN HIDDEN WORLD</p><h2>Explore your cave</h2></div><button class="text-button" data-go="welcome">Leave cave</button></div><button class="mood-checkin" data-action="mood">'+(store.mood?'Atmosphere: '+esc(moodOptions[store.mood]?.label||'Personal')+' · Change':'How are you feeling? · Optional')+'</button><p class="map-hint">Drag or swipe to explore · Tap a room to enter<br>Double-tap to move closer</p><div class="cave-viewport" tabindex="0" role="region" aria-label="Explore cave. Scroll or use arrow keys to move; Tab to room markers."><div class="cave-panorama" style="width:'+caveBaseWidth()*caveZoom+'px;height:'+660*caveZoom+'px"><img class="cave-map-art" src="'+APP_ASSETS.interior+'" alt="A spacious cavern with pathways and room entrances" draggable="false"><div class="cave-atmosphere" aria-hidden="true"><i class="cave-glow"></i><i class="cave-water"></i><i class="cave-mote mote-one"></i><i class="cave-mote mote-two"></i><i class="cave-mote mote-three"></i></div>'+store.worlds.map((w,i)=>{const x=store.worlds.length<=6?[270,530,820,160,450,730][i]:150+Math.floor(i/3)*230;const y=store.worlds.length<=6?[300,205,350,475,470,505][i]:[220,355,490][i%3];return '<button class="room-marker" style="left:'+(x/caveBaseWidth()*100)+'%;top:'+(y/660*100)+'%" data-enter-room="'+esc(w.id)+'" aria-label="Enter '+esc(w.name)+'"><img src="'+APP_ASSETS.worlds[w.environment]+'" alt="" draggable="false"><span>'+esc(w.name)+'</span></button>'}).join('')+(!store.worlds.length?'<div class="map-empty"><strong>Your cave awaits.</strong><p>Create your first room and its doorway will appear here.</p></div>':'')+'</div></div><div class="map-controls"><button class="icon-button" data-pan="-1" aria-label="Explore left">'+icon('back')+'</button><span class="cave-depth-label">'+Math.round(caveZoom*100)+'% · 2D exploration preview</span><button class="icon-button" data-pan="1" aria-label="Explore right">'+icon('arrow')+'</button></div>'+'<div class="cave-depth-controls"><button class="text-button" data-cave-zoom="reset" '+(caveZoom<=1?'disabled':'')+'>Step back</button><button class="text-button" data-cave-zoom="closer" '+(caveZoom>=1.8?'disabled':'')+'>Move closer</button></div>'+button('+ Create a room','create-room','secondary')+'<button class="tertiary" data-go="compare">Explore two new rooms</button>';}
if(screen==='compare'){const w={environment:comparisonRoom,vibe:comparisonRoom==='grotto'?'Fresh':'Cozy'};content=header('Find your kind of comfort','home')+'<p class="overline">TWO ROOMS TO EXPLORE</p><h1 class="title">Where feels like you?</h1><div class="option-grid">'+['grotto','hearth'].map(id=>'<button class="option '+(comparisonRoom===id?'selected':'')+'" data-compare-room="'+id+'" aria-pressed="'+(comparisonRoom===id)+'">'+environments[id]+'</button>').join('')+'</div>'+worldVisual(w,false,comparisonCompany)+'<p class="subtitle">'+(comparisonRoom==='grotto'?'Open views, pale stone and soft daylight.':'Warm stone, books and a glowing hearth.')+'</p><p class="section-label">Keep the same company</p><div class="option-grid">'+[['none','Just me'],...companions.map(c=>[c.id,c.name])].map(([id,name])=>'<button class="option '+(comparisonCompany===id?'selected':'')+'" data-compare-company="'+id+'" aria-pressed="'+(comparisonCompany===id)+'">'+name+'</button>').join('')+'</div>'+button('Make this room mine','use-compared-room')+'<p class="disclosure">Illustrated design concepts. Choose what feels comfortable to you; neither room is a proven treatment.</p>';}
if(screen==='room'){const w=activeWorld(),c=companion();cls='room-screen';content=header(esc(w.name),'home','<details class="room-more"><summary aria-label="More room options">•••</summary><div class="room-more-panel">'+button('Edit room','customize','text-button')+button('Bookshelf','books','text-button')+button('Check in with yourself','mood','text-button')+'<p class="card-sub">'+esc(environments[w.environment])+' · '+esc(w.vibe)+'</p></div></details>')+'<div class="room-scene">'+worldVisual(w,false,store.presence==='alone'?'none':c.id)+'<div class="room-presence"><span class="presence-dot"></span>'+(store.presence==='alone'?'Just me':store.presence==='quiet'?'Quiet company with '+c.name:'Talk together with '+c.name)+'</div></div><div class="room-controls"><button class="secondary" data-go="activities">'+icon('activities')+'<span>Activities</span></button><button class="secondary" data-go="room-notes">'+icon('saved')+'<span>Notebook</span></button><button class="secondary" data-action="company">'+icon('chat')+'<span>Company</span></button></div>'+(store.presence==='talk'?button(messages.length?'Continue conversation':'Talk with '+c.name,'start','primary','arrow'):'<p class="room-caption">'+(store.presence==='quiet'?'A little company. No need to talk.':'Your room. Your pace.')+'</p>')+roomShelf();}
if(screen==='chat'){cls='chat-screen';content='<div class="header"><button class="icon-button" data-go="room" aria-label="Back to room">'+icon('back')+'</button><div><h2>'+companion().name+' · AI</h2><p class="card-sub">'+esc(store.connectionRole)+'</p></div><button class="text-button" data-go="finish">End</button></div>'+worldVisual(activeWorld(),true)+'<div class="chat-meta"><span class="pill">'+esc(store.style)+' style</span><button class="text-button" data-action="company">Company</button></div><p class="demo-label">Interactive demo · sample AI replies</p><div class="messages" aria-live="polite">'+messages.map(m=>'<div class="bubble '+(m.role==='user'?'user':'')+'">'+(m.role==='ai'?'<span class="speaker">'+esc((m.speakerName||'AI companion').toUpperCase())+' · AI</span>':'')+esc(m.text)+'</div>').join('')+'</div>'+(messages.length===1?'<button class="suggestion" data-action="suggest">I keep thinking about work.</button>':'')+'<form class="composer" id="chat-form"><input id="chat-input" aria-label="Your message" placeholder="What’s on your mind?" maxlength="2000" autocomplete="off"><button aria-label="Send message" type="submit">'+icon('send')+'</button></form><p class="disclosure" style="margin:8px 0 0">Demo text stays in this browser. Avoid sensitive details.</p>'}
if(screen==='finish'){content=header('A moment to close','chat')+'<div class="finish-icon">'+icon('leaf')+'</div><h1 class="title center">Take what you need.<br>Leave the rest here.</h1><p class="subtitle center">Keep this conversation to revisit later,<br>or finish without saving it.</p><label class="field-label" for="chat-title">Conversation title</label><input class="input" id="chat-title" maxlength="80" value="Evening reflection"><label class="field-label" for="takeaway">A thought to keep (optional)</label><textarea id="takeaway" maxlength="600" placeholder="In your own words…"></textarea><p class="disclosure">Saved conversations are stored only in this browser on this device. Anyone using it may be able to read them.</p><div class="space"></div>'+button('Save conversation','save')+button('Finish without saving','discard','tertiary')+button('Keep talking','keep','secondary')}
if(screen==='saved'){content='<p class="overline">YOUR PERSONAL SPACE</p><h1 class="title">Saved moments</h1><p class="subtitle">A place to come back to your thoughts.</p>'+(store.chats.length?store.chats.map(c=>'<button class="card" data-chat="'+esc(c.id)+'"><p class="saved-date">'+esc(new Date(c.created).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}))+'</p><div class="row"><p class="card-title">'+esc(c.title)+'</p><span style="width:18px">'+icon('chevron')+'</span></div><p class="card-sub">'+esc(c.worldName||'Evening lounge')+' · '+esc(c.companionName||'AI companion')+'</p></button>').join(''):'<div class="empty"><span class="mini-icon">'+icon('saved')+'</span><h2 class="card-title">Your room is ready.</h2><p class="subtitle">Conversations you choose to save<br>will appear here.</p>'+button('Start a conversation','start','secondary')+'</div>')+'<p class="disclosure">Stored in this browser only. Clearing browser data removes your saved conversations.</p>'}
if(screen==='saved'){content+='<p class="section-label">Your books</p>'+button('Open all books ('+store.books.length+')','all-books','secondary')+'<p class="section-label">Your notebook</p>'+(store.notes.length?store.notes.map(n=>'<button class="card" data-note="'+esc(n.id)+'"><p class="card-title">'+esc(n.title)+'</p><p class="card-sub">'+esc(n.room)+' · '+esc(new Date(n.created).toLocaleDateString())+'</p></button>').join(''):'<p class="card-sub">Notes you save will appear here.</p>');}
if(screen==='room-notes'){const w=activeWorld(),notes=store.notes.filter(n=>notesFilter==='all'||(n.roomId?n.roomId===w.id:n.room===w.name));content=header('Notebook','room')+'<p class="overline">'+esc(w.name)+'</p><h1 class="title">Your thoughts,<br>close by.</h1><div class="note-filters" role="group" aria-label="Filter notes"><button data-notes-filter="room" aria-pressed="'+(notesFilter==='room')+'">This room</button><button data-notes-filter="all" aria-pressed="'+(notesFilter==='all')+'">All notes</button></div><button class="primary" data-go="notebook">'+(noteDraft||noteTitle?'Continue draft':'New note')+'</button>'+(notes.length?notes.map(n=>'<button class="card note-card" data-note="'+esc(n.id)+'"><p class="saved-date">'+esc(new Date(n.created).toLocaleDateString(undefined,{month:'short',day:'numeric'}))+' · '+esc(n.room||'Your notebook')+'</p><p class="card-title">'+esc(n.title)+'</p><p class="note-excerpt">'+esc((n.text||'').slice(0,150))+'</p></button>').join(''):'<div class="notebook-empty"><span>'+icon('saved')+'</span><p class="card-title">A fresh page awaits.</p><p class="card-sub">'+(notesFilter==='room'?'Notes you save in this room will appear here.':'Your saved thoughts will appear here.')+'</p></div>')+'<p class="disclosure">Stored only in this browser · not shared with companions</p>';}

if(screen==='music'){content=header('Sound',musicReturn)+'<p class="overline">YOUR ATMOSPHERE</p><h1 class="title">Make yourself<br>comfortable.</h1><div class="sound-status"><span class="presence-dot"></span><p id="sound-state" role="status">Paused</p><button class="secondary" data-action="sound-toggle">Play</button></div><p class="section-label">Ambient music</p>'+[['warm','Warm stillness','Soft, low chords'],['float','Floating light','Higher, spacious tones'],['deep','Deep calm','Slow, low resonance']].map(([id,title,desc])=>'<button class="card choice '+((store.musicTrack||'warm')===id?'selected':'')+'" data-music-track="'+id+'" aria-pressed="'+((store.musicTrack||'warm')===id)+'"><span class="card-content"><strong>'+title+'</strong><span class="card-sub">'+desc+'</span></span><span class="radio"></span></button>').join('')+'<label class="field-label" for="music-volume">Volume <output id="volume-label">'+Math.round((store.musicVolume??.6)*100)+'%</output></label><input id="music-volume" type="range" min="0" max="100" value="'+Math.round((store.musicVolume??.6)*100)+'" aria-label="Music volume"><p class="disclosure">Original ambient scores. Your music and volume choices are remembered.</p>';}

if(screen==='rest'){cls='rest-screen';content='<div class="rest-scene">'+worldVisual(activeWorld(),false,'none')+'</div><div class="rest-overlay"><p class="overline">'+esc(activeWorld().name)+'</p><h1 class="title">Nothing to do.<br>Just be here.</h1></div><div class="rest-actions"><button class="rest-control" data-action="music-menu">Sound</button><button class="rest-control" data-go="room">Exit rest</button></div>';}

if(screen==='notebook'){content=header('New note','room-notes')+'<h1 class="title">A little space<br>for your thoughts.</h1><p class="subtitle">Write freely, or use the optional prompt below.</p><label class="field-label" for="note-title">Title (optional)</label><input class="input" id="note-title" maxlength="80" value="'+esc(noteTitle)+'" placeholder="A thought to keep"><label class="field-label" for="note-body">Your note</label><textarea id="note-body" class="notebook-body" maxlength="10000" placeholder="Start wherever you are…">'+esc(noteDraft)+'</textarea><details><summary>A gentle starting point</summary><p class="card-sub">What is on your mind, and what would you like to leave for another day?</p></details>'+button('Save note','save-note')+'<p class="disclosure">Not shared with companions. Saved only in this browser, without encryption. Anyone using this browser may be able to read it. Unsaved writing lasts only for this visit.</p>';}
if(screen==='note-detail'){const n=store.notes.find(n=>n.id===openedNote);if(!n){screen='saved';render();return}content=header('Saved note',noteReturn)+'<p class="overline">'+esc(n.room)+'</p><h1 class="title">'+esc(n.title)+'</h1><div class="card note-text">'+esc(n.text)+'</div><p class="disclosure">Not shared with companions · stored in this browser</p><div id="note-delete">'+button('Delete note','ask-delete-note','tertiary danger')+'</div>';}
if(screen==='detail'){const c=store.chats.find(c=>c.id===currentId);if(!c){screen='saved';render();return}content=header('Saved conversation','saved')+'<p class="saved-date">'+esc(new Date(c.created).toLocaleDateString())+' · '+esc(c.worldName||'Evening lounge')+'</p><h1 class="title" style="font-size:27px">'+esc(c.title)+'</h1><label class="field-label" for="rename">Title</label><div class="row"><input class="input" id="rename" value="'+esc(c.title)+'" maxlength="80"><button class="text-button" data-action="rename">Rename</button></div>'+(c.takeaway?'<p class="section-label">Your takeaway</p><div class="card"><p class="card-sub">'+esc(c.takeaway)+'</p></div>':'')+'<p class="section-label">Conversation</p>'+c.messages.map(m=>'<div class="bubble '+(m.role==='user'?'user':'')+'"><span class="speaker">'+(m.role==='user'?'YOU':esc((m.speakerName||'AI companion').toUpperCase())+' · SAMPLE REPLY')+'</span>'+esc(m.text)+'</div>').join('')+(c.unsentDraft?'<p class="section-label">Unsent draft</p><div class="card"><p class="card-sub">'+esc(c.unsentDraft)+'</p></div>':'')+'<div id="delete-area">'+button('Delete conversation','ask-delete','tertiary danger')+'</div>'}
if(screen==='activities'){content=header('Activities',activityReturn)+'<p class="overline">A DIFFERENT KIND OF PAUSE</p><h1 class="title">Follow your mood.</h1><p class="subtitle">Settle your thoughts or spark your curiosity.<br>There’s no right way to take a break.</p><button class="card" data-go="rest"><p class="card-title">Just rest</p><p class="card-sub">Hide the controls. Stay for a moment.</p></button><button class="card" data-go="room-notes"><p class="card-title">Your notebook</p><p class="card-sub">A thought, a reflection, a place to write.</p></button><button class="card" data-action="books"><p class="card-title">Your bookshelf</p><p class="card-sub">Read in your room. Pick up where you stopped.</p></button><p class="section-label">Slow things down</p><button class="card" data-action="meditate"><div class="activity-art"><div class="orb"></div></div><div class="row"><div><p class="card-title">After-work pause</p><p class="card-sub">3 min · Breathing visual</p></div><span class="mini-icon">'+icon('play')+'</span></div></button><button class="card row" data-action="quick-meditate"><span class="mini-icon">'+icon('leaf')+'</span><div class="card-content"><p class="card-title">Quiet breathing</p><p class="card-sub">2 min · A gentler rhythm</p></div><span style="width:20px">'+icon('chevron')+'</span></button><p class="section-label">Give your mind a little play</p><button class="card" data-go="game"><div class="activity-art game-art"><span></span><span></span><span></span></div><div class="row"><div><p class="card-title">Pattern pause</p><p class="card-sub">Untimed · Remember the sequence</p></div><span class="mini-icon">'+icon('arrow')+'</span></div></button>'}
if(screen==='meditation'){cls='meditation';content=header(medTotal===180?'After-work pause':'Quiet breathing',meditationReturn)+'<p class="overline">LET THE DAY SETTLE</p><h1 class="title">Nothing to solve.<br>Just a little space.</h1><p class="subtitle">Breathe comfortably. Follow the rhythm<br>if it feels good, or simply rest here.</p><div class="breathing-area"><div class="breathing-orb" aria-hidden="true"></div></div><p id="breath-label" class="card-title">'+(seconds<medTotal?'Paused. Take your time.':'Ready when you are')+'</p><p class="timer" id="timer">'+formatTime(seconds)+'</p><div class="progress"><div id="progress" style="width:'+((medTotal-seconds)/medTotal*100)+'%"></div></div><button class="play-circle" data-action="play" aria-label="'+(seconds<medTotal?'Resume meditation':'Start meditation')+'">'+icon('play')+'</button><button class="tertiary" data-go="'+meditationReturn+'">Finish this pause</button><p class="disclosure">Visual breathing timer · optional background music</p>'}
if(screen==='game'){content=header('Pattern pause','activities')+'<p class="overline">A LITTLE PLAY, NO PRESSURE</p><h1 class="title">Find the rhythm.</h1><p class="subtitle">Watch the tiles light up, then tap them<br>in the same order. Take your time.</p><div class="row"><span class="pill" id="level">Round 1</span><span class="card-sub">No timer. No score.</span></div><div class="game-grid">'+Array.from({length:9},(_,i)=>'<button class="tile" data-tile="'+i+'" aria-label="Tile '+(i+1)+'" disabled></button>').join('')+'</div><p class="game-message" id="game-message">Ready for a change of pace?</p>'+button('Show me the pattern','game-start')+'<button class="tertiary" data-go="activities">I’m ready to finish</button>'}

if(screen==='books'){content=booksView();}
if(screen==='reader'){if(!readingBook()){screen='books';render();return}cls='reader-screen';content=readerView();}
if(screen==='book-manage'){if(!readingBook()){screen='books';render();return}content=manageBookView();}
if(screen==='add-book'){content=header('Add a book','books')+'<h1 class="title">Make room for a story.</h1><label class="secondary book-import" for="book-file">Import a text book<input id="book-file" type="file" accept=".txt,text/plain"></label><p class="disclosure">Plain UTF-8 .txt only · up to 500 KB. PDF and EPUB are not supported yet. Nothing is uploaded.</p><p class="section-label">Choose from your library</p>'+store.books.filter(b=>!b.roomIds.includes(activeWorld().id)).map(b=>'<button class="card" data-book-add="'+esc(b.id)+'"><strong>'+esc(b.title)+'</strong><p class="card-sub">Add to this room · progress stays with you</p></button>').join('')+button('Try an original reading sample','sample-book','tertiary');}
if(screen==='import-book'&&importDraft){content=header('Your new book','add-book')+'<p class="overline">IMPORT PREVIEW</p><h1 class="title">A place on your shelf.</h1><label class="field-label" for="import-title">Book title</label><input class="input" id="import-title" maxlength="150" value="'+esc(importDraft.title)+'"><div class="card"><p class="card-sub">'+esc(importDraft.text.slice(0,230))+'…</p></div><p class="disclosure">Save to your library and '+esc(activeWorld().name)+'. A typographic cover is created from the title.</p>'+button('Save book & read','save-import');}
if(screen==='mood'){const m=moodOptions[moodChoice];content=header('A moment for you',moodReturn)+'<h1 class="title">How are you<br>feeling now?</h1><p class="subtitle">Optional. Choose an atmosphere to try.<br>You can always keep things as they are.</p><div class="option-grid">'+Object.entries(moodOptions).map(([id,m])=>'<button class="option '+(moodChoice===id?'selected':'')+'" data-mood="'+id+'" aria-pressed="'+(moodChoice===id)+'">'+m.label+'</button>').join('')+'</div>'+(m?'<div class="card mood-preview mood-preview-'+moodChoice+'"><p class="card-title">'+m.title+'</p><p class="card-sub">'+m.description+'</p></div>'+button('Apply atmosphere','apply-mood'):'')+button('Keep current atmosphere','skip-mood','tertiary')+(store.moodUndo?button('Undo last atmosphere change','undo-mood','secondary'):'')+(store.moodOriginal?button('Reset original atmosphere','reset-mood','tertiary'):'')+'<p class="disclosure">A personal preference, not a treatment. We remember only your latest selection on this device, not a mood history. Your room design and companion stay the same.</p>';}

if(screen==='settings'){content=(location.protocol!=='file:'?'<a class="secondary" href="cloud.html">Cloud backup &amp; sign-in</a>':'')+'<p class="overline">MAKE IT YOURS</p><h1 class="title">Settings</h1><p class="subtitle">Your account, your worlds, your pace.</p><p class="section-label">Account · local demo</p><div class="card"><p class="card-title">'+esc(store.profile?.name||'Guest')+'</p><p class="card-sub">'+(store.loggedIn?'Logged in to this device demo':'Logged out')+'</p><label class="field-label" for="account-name">Display name</label><input class="input" id="account-name" maxlength="40" value="'+esc(store.profile?.name||'')+'">'+button('Save account name','save-account','secondary')+'</div>'+button(store.loggedIn?'Log out of demo':'Log in to demo',store.loggedIn?'logout':'enter','secondary')+'<p class="disclosure">This is a local demo profile, not secure authentication. Anyone using this browser can access its saved data. Logging out keeps your worlds and chats on this device.</p><p class="section-label">App preferences</p><div class="card row"><div class="card-content"><p class="card-title">Reduce motion</p><p class="card-sub">Keep animated visuals still.</p></div><button class="toggle '+(store.reduced?'on':'')+'" data-action="motion" role="switch" aria-label="Reduce motion" aria-checked="'+store.reduced+'"></button></div>'+button('Back to my cave','home','secondary')+'<p class="section-label">About this experience</p><div class="card"><p class="card-title">A playful space to reflect</p><p class="card-sub">AI companions are fictional characters, not human therapists. Replies are scripted samples, not live AI or clinical care. This demo cannot provide crisis support.</p></div><div id="delete-area">'+button('Reset all demo data','ask-reset','tertiary danger')+'</div>'}
$('#app').dataset.atmosphere=store.mood||'';$('#app').classList.toggle('reduced',store.reduced);$('#app').innerHTML='<div class="status" aria-hidden="true"><span>9:41</span><span class="status-icons">'+icon('signal')+icon('battery')+'</span></div><section class="screen '+cls+'">'+content+'</section>'+(['home','saved','settings'].includes(screen)?nav():'');if(screen==='chat'){$('.messages').scrollTop=$('.messages').scrollHeight;$('#chat-input').value=draft;$('.chat-screen').classList.toggle('composing',!!draft);$('#chat-input').addEventListener('input',()=>{$('.chat-screen').classList.toggle('composing',!!$('#chat-input').value)});$('#chat-form').addEventListener('submit',e=>{e.preventDefault();sendMessage($('#chat-input').value)})}if(screen==='home')initCaveMap();window.ambientMusic?.sync();if(detailsOpen&&$('details'))$('details').open=true;if(focusAttr){const attr=focusAttr.replace(/[A-Z]/g,c=>'-'+c.toLowerCase());document.querySelector('[data-'+attr+'="'+CSS.escape(focusValue)+'"]'+(focusChoice?'[data-value="'+CSS.escape(focusChoice)+'"]':''))?.focus({preventScroll:true})}}
function sendMessage(value){value=value.trim();if(!value)return;messages.push({role:'user',worldName:activeWorld().name,text:value});let reply;const round=messages.filter(m=>m.role==='user').length;const replies={Gentle:['It can be hard to leave a busy day behind. What part of today is still on your mind?','You can take your time with that. What would feel like a small kindness to yourself tonight?','Thanks for making room for that thought. Would you like to keep reflecting or take a quiet pause?'],Reflective:['What part of today keeps coming back to you?','What do you notice about the way that moment made you feel?','What would you like to carry forward from this reflection?'],Practical:['What is one thing from today that you would like to set aside for tonight?','What is one small step you could take tomorrow? You could write it down, then give yourself permission to pause.','Would a short breathing pause or a few minutes of a pattern game suit you now?']};reply=replies[store.style][(round-1)%3];messages.push({role:'ai',speakerName:companion().name,worldName:activeWorld().name,text:reply});draft='';render();$('.messages .bubble:last-child')?.classList.add('response-ready');$('#chat-input').focus()}
function formatTime(s){return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
let medTotal=180;
function toggleMeditation(){if(playing){clearInterval(medTimer);playing=false;$('.breathing-orb').classList.remove('playing');$('.play-circle').innerHTML=icon('play');$('.play-circle').setAttribute('aria-label','Resume meditation');$('#breath-label').textContent='Take your time';return}if(seconds<=0)seconds=medTotal;playing=true;$('.breathing-orb').classList.add('playing');$('.play-circle').innerHTML=icon('pause');$('.play-circle').setAttribute('aria-label','Pause meditation');$('#breath-label').textContent='Breathe in, gently';medTimer=setInterval(()=>{seconds--;$('#timer').textContent=formatTime(seconds);$('#progress').style.width=((medTotal-seconds)/medTotal*100)+'%';$('#breath-label').textContent=(medTotal-seconds)%8<4?'Breathe in, gently':'Breathe out, slowly';if(seconds<=0){clearInterval(medTimer);playing=false;$('.breathing-orb').classList.remove('playing');$('#breath-label').textContent='A little space, just for you.';$('.play-circle').innerHTML=icon('play');$('.play-circle').setAttribute('aria-label','Restart meditation')}},1000)}
function showPattern(){gameTimeouts.forEach(clearTimeout);gameTimeouts=[];gameReady=false;guess=0;$('.primary').disabled=true;document.querySelectorAll('.tile').forEach(t=>{t.disabled=true;t.classList.remove('lit')});$('#game-message').textContent='Watch the pattern…';$('#level').textContent='Round '+gameLevel;sequence=Array.from({length:Math.min(gameLevel+1,7)},()=>Math.floor(Math.random()*9));sequence.forEach((v,i)=>{gameTimeouts.push(setTimeout(()=>{$('[data-tile="'+v+'"]').classList.add('lit')},500+i*850));gameTimeouts.push(setTimeout(()=>{$('[data-tile="'+v+'"]').classList.remove('lit')},1050+i*850))});gameTimeouts.push(setTimeout(()=>{gameReady=true;document.querySelectorAll('.tile').forEach(t=>t.disabled=false);$('#game-message').textContent='Your turn. Tap the tiles in order.'},550+sequence.length*850))}
$('#app').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.dataset.book){readingId=b.dataset.book;bookDelete=false;readerBookmarks=false;const book=readingBook();if(book){book.lastRead=Date.now();persist();go('reader')}return}
if(b.dataset.booksFilter){booksFilter=b.dataset.booksFilter;render();return}
if(b.dataset.bookManage){readingId=b.dataset.bookManage;bookDelete=false;go('book-manage');return}
if(b.dataset.bookAdd){const book=store.books.find(x=>x.id===b.dataset.bookAdd);const old=[...book.roomIds];book.roomIds.push(activeWorld().id);if(persist()){booksFilter='room';go('books');toast('Added to this room.')}else book.roomIds=old;return}
if(b.dataset.bookRoom){const book=readingBook(),old=[...book.roomIds],id=b.dataset.bookRoom;book.roomIds=old.includes(id)?old.filter(x=>x!==id):[...old,id];if(persist())render();else book.roomIds=old;return}
if(b.dataset.readerTheme){const book=readingBook(),old=book.theme;book.theme=b.dataset.readerTheme;if(persist())render();else book.theme=old;return}
if(b.dataset.bookmarkJump!==undefined){const book=readingBook(),old=book.page;book.page=Number(b.dataset.bookmarkJump);if(persist()){render();$('.screen').scrollTop=0}else book.page=old;return}
if(b.dataset.bookmarkRemove!==undefined){const book=readingBook(),old=book.bookmarks;book.bookmarks=old.filter(m=>m.page!==Number(b.dataset.bookmarkRemove));if(persist())render();else book.bookmarks=old;return}
if(b.dataset.bookPage||b.dataset.bookFont){const book=readingBook();if(!book)return;const field=b.dataset.bookPage?'page':'font',old=book[field];book[field]=field==='page'?Math.max(0,Math.min(book.pages.length-1,old+Number(b.dataset.bookPage))):Math.max(16,Math.min(26,old+Number(b.dataset.bookFont)));if(persist()){render();$('.screen').scrollTop=0}else book[field]=old;return}
if(b.dataset.mood){moodChoice=b.dataset.mood;render();return}
if(b.dataset.notesFilter){notesFilter=b.dataset.notesFilter;render();$('[data-notes-filter="'+notesFilter+'"]')?.focus();return}if(b.dataset.compareRoom){comparisonRoom=b.dataset.compareRoom;render();return}if(b.dataset.compareCompany){comparisonCompany=b.dataset.compareCompany;render();return}
if(b.dataset.caveZoom){moveCaveCloser(null,null,b.dataset.caveZoom==='reset');return}
if(b.dataset.pan){const v=$('.cave-viewport');v.scrollLeft+=Number(b.dataset.pan)*220;return}
if(b.dataset.musicTrack){const old=store.musicTrack;store.musicTrack=b.dataset.musicTrack;if(persist()){window.ambientMusic?.changeTrack();render()}else store.musicTrack=old;return}
if(b.dataset.note){noteReturn=screen==='room-notes'?'room-notes':'saved';openedNote=b.dataset.note;go('note-detail');return}
if(b.dataset.enterRoom){if(b.dataset.enterRoom!==store.activeWorld&&finishBeforeRoomChange())return;const old={activeWorld:store.activeWorld,selectedCompanion:store.selectedCompanion,presence:store.presence,style:store.style};store.activeWorld=b.dataset.enterRoom;restoreRoomCompany();if(persist())go('room');else Object.assign(store,old);return}
if(b.dataset.presence){custom.presence=b.dataset.presence;render();return}
if(b.dataset.roomStyle){captureWorld();const w=draftWorld();w.vibe=b.dataset.roomStyle;w.environment={Cozy:'hearth',Fresh:'grotto',Futuristic:'ocean',Calm:'ocean'}[w.vibe];render();return}
if(b.dataset.customTab){captureWorld();customTab=b.dataset.customTab;render();return}
if(b.dataset.worldField){captureWorld();draftWorld()[b.dataset.worldField]=b.dataset.value;render();return}
if(b.dataset.companion){custom.selectedCompanion=b.dataset.companion;render();return}
if(b.dataset.selectWorld){captureWorld();custom.activeWorld=b.dataset.selectWorld;render();return}
if(b.dataset.go){if(b.dataset.go==='activities'&&screen!=='game'&&screen!=='meditation')activityReturn=screen==='rest'?'rest':'room';if(b.dataset.go==='room-notes'&&screen==='room')notesFilter='room';if(b.dataset.go==='game')gameLevel=1;go(b.dataset.go);return}if(b.dataset.style){custom.style=b.dataset.style;render();return}if(b.dataset.chat){currentId=b.dataset.chat;go('detail');return}if(b.dataset.tile!==undefined){if(!gameReady)return;const n=Number(b.dataset.tile);b.classList.add('lit');gameTimeouts.push(setTimeout(()=>b.classList.remove('lit'),220));if(n!==sequence[guess]){gameReady=false;$('#game-message').textContent='Not quite. No rush — try a new pattern.';$('.primary').textContent='Try again';$('.primary').disabled=false;document.querySelectorAll('.tile').forEach(t=>t.disabled=true);return}guess++;if(guess===sequence.length){gameReady=false;$('#game-message').textContent='You found it. Ready for a little more?';gameLevel++;$('.primary').textContent='Next pattern';$('.primary').disabled=false;document.querySelectorAll('.tile').forEach(t=>t.disabled=true)}return}switch(b.dataset.action){
case'books':booksFilter='room';go('books');break;case'all-books':booksFilter='all';go('books');break;
case'add-book':go('add-book');break;case'save-import':{const title=$('#import-title').value.trim();if(!title){toast('Give your book a title.');break}addBook(title,importDraft.text);break}
case'toggle-bookmark':{const book=readingBook(),old=book.bookmarks;book.bookmarks=old.some(m=>m.page===book.page)?old.filter(m=>m.page!==book.page):[...old,{page:book.page,offset:book.pages.slice(0,book.page).join('').length}].sort((a,b)=>a.page-b.page);if(persist()){render();toast('Bookmarks updated.')}else book.bookmarks=old;break}
case'show-bookmarks':readerBookmarks=!readerBookmarks;render();break;
case'sample-book':{const existing=store.books.find(b=>b.sample);if(existing){const old=[...existing.roomIds];if(!old.includes(activeWorld().id))existing.roomIds.push(activeWorld().id);if(!persist()){existing.roomIds=old;break}readingId=existing.id;bookDelete=false;go('reader')}else addBook('The Lantern Keeper',SAMPLE_READING,true);break}
case'ask-delete-book':bookDelete=true;render();break;case'keep-book':bookDelete=false;render();break;
case'delete-book':{const old=store.books;store.books=store.books.filter(b=>b.id!==readingId);if(persist()){readingId=null;bookDelete=false;go('books')}else store.books=old;break}
case'mood':moodReturn=screen==='home'?'home':'room';moodChoice=null;go('mood');break;case'apply-mood':applyMood();break;case'skip-mood':go(moodReturn);break;case'undo-mood':restoreMood();break;case'reset-mood':restoreMood(true);break;
case'login':{const name=$('#profile-name').value.trim();if(!name){toast('Add a name to create your space.');$('#profile-name').focus();break}const old={profile:store.profile,loggedIn:store.loggedIn};store.profile={name};store.loggedIn=true;store.sessionClosed=false;const saved=persist();if(store.worlds.length)go('home');else openCustomize('space',true);if(!saved)toast('Using a temporary profile. Storage is unavailable.');break}
case'logout':{if(messages.length||draft.trim()){toast('Finish your conversation before logging out.');go('finish');break}store.loggedIn=false;store.sessionClosed=true;if(persist()){draft='';messages=[];go('welcome')}else {store.loggedIn=true;store.sessionClosed=false}break}
case'save-account':{const name=$('#account-name').value.trim();if(!name){toast('Please enter a name.');break}const old=store.profile;store.profile={name};if(persist()){render();toast('Account name updated.')}else store.profile=old;break}
case'use-compared-room':{if(finishBeforeRoomChange())break;openCustomize('space');custom.presence=comparisonCompany==='none'?'alone':'quiet';if(comparisonCompany!=='none')custom.selectedCompanion=comparisonCompany;const w={id:'world-'+Date.now(),name:environments[comparisonRoom],environment:comparisonRoom,vibe:comparisonRoom==='grotto'?'Fresh':'Cozy',prompt:comparisonRoom==='grotto'?'A sunlit grotto with plants and open views':'A warm hearth room with books and a fireplace'};custom.worlds.push(w);custom.activeWorld=w.id;worldReturn='room';render();break}case'save-note':{const text=$('#note-body').value.trim();if(!text){toast('Write a thought before saving.');break}const n={id:'note-'+Date.now(),title:$('#note-title').value.trim()||'A thought to keep',text,roomId:activeWorld().id,room:activeWorld().name,created:new Date().toISOString()};store.notes.unshift(n);if(persist()){delete noteDrafts[activeWorld().id];noteDraft='';noteTitle='';screen='room-notes';notesFilter='room';render();toast('Note saved in your notebook.')}else store.notes.shift();break}case'ask-delete-note':$('#note-delete').innerHTML='<p class="card-sub">Delete this note permanently?</p>'+button('Delete note','delete-note','secondary danger')+button('Keep note','keep-note','tertiary');break;case'keep-note':render();break;case'delete-note':{const old=store.notes;store.notes=store.notes.filter(n=>n.id!==openedNote);if(persist())go(noteReturn);else store.notes=old;break}case'music-menu':if(screen!=='music')musicReturn=screen;go('music');break;case'company':openCustomize('companion');break;case'create-room':if(finishBeforeRoomChange())break;openCustomize('space',!store.worlds.length);if(store.worlds.length){const w={id:'world-'+Date.now(),name:'My new room',environment:'lounge',vibe:'Cozy',prompt:''};custom.worlds.push(w);custom.activeWorld=w.id;worldReturn='room';render()}break;case'preview-room':{captureWorld();const w=draftWorld(),p=w.prompt.toLowerCase();if(/future|space|neon|sci.fi|cyber/.test(p))w.vibe='Futuristic';else if(/forest|fresh|plant|garden|sunlit|grotto|daylight/.test(p))w.vibe='Fresh';else if(/sea|ocean|calm|water/.test(p))w.vibe='Calm';else if(/cozy|fire|warm|book|hearth/.test(p))w.vibe='Cozy';w.environment={Cozy:'hearth',Fresh:'grotto',Futuristic:'ocean',Calm:'ocean'}[w.vibe];render();toast('Matching preset previewed. Save when ready.');break}case'restore-room':{const w=draftWorld(),current={...w};delete current.previous;Object.assign(w,w.previous,{previous:current});render();toast('Previous design previewed. Save to restore.');break}case'onboard-back':customTab='space';render();break;case'customize':openCustomize();break;
case'cancel-custom':custom=null;go(onboarding?'welcome':worldReturn);onboarding=false;break;
case'new-world':{captureWorld();const w={id:'world-'+Date.now(),name:'My new space',environment:'lounge',vibe:'Cozy'};custom.worlds.push(w);custom.activeWorld=w.id;render();break}
case'apply-custom':captureWorld();if(customTab==='space'){const w=draftWorld(),old=store.worlds.find(v=>v.id===w.id);if(old){w.previous={...old};delete w.previous.previous}}if(messages.length&&custom.selectedCompanion!==store.selectedCompanion){go('switch-companion');break}applyCustom();break;
case'switch-continue':applyCustom();break;
case'switch-fresh':applyCustom(true);break;
case'switch-cancel':go('customize');break;
case'ask-reset':$('#delete-area').innerHTML='<div class="delete-confirm"><p>Reset this demo? Your local profile, worlds, preferences, books, notes, and saved conversations will be deleted. This cannot be undone.</p>'+button('Delete all demo data','reset','secondary danger')+button('Cancel','cancel-delete','tertiary')+'</div>';break;
case'reset':{const old=store;store={books:[],notes:[],chats:[],style:'Gentle',reduced:false,profile:null,worlds:[],activeWorld:null,loggedIn:false,selectedCompanion:'maya',connectionRole:'Reflection partner'};if(persist()){messages=[];draft='';noteDraft='';noteTitle='';Object.keys(noteDrafts).forEach(k=>delete noteDrafts[k]);worldDraft=null;go('welcome');toast('Demo data reset.')}else store=old;break}
case'enter':if(screen==='settings')go('login');else{store.sessionClosed=false;if(persist())go('home')};break;case'home':go('home');break;case'start':if(!store.worlds.length){openCustomize('space',true);break}store.presence='talk';activeWorld().presence='talk';persist();beginChat();break;case'suggest':sendMessage('I keep thinking about work.');break;case'keep':go('chat');break;case'discard':messages=[];draft='';go('home');toast('Finished without saving.');break;case'save':{const c={id:Date.now().toString(36),created:new Date().toISOString(),title:$('#chat-title').value.trim()||'Evening reflection',takeaway:$('#takeaway').value.trim(),worldName:activeWorld().name,companionName:companion().name,unsentDraft:draft,messages:messages.map(m=>({...m}))};store.chats.unshift(c);if(persist()){messages=[];draft='';go('saved');toast('Conversation saved on this device.')}else store.chats.shift();break}case'rename':{const c=store.chats.find(c=>c.id===currentId);const title=$('#rename').value.trim();if(!title){toast('Please enter a title.');break}const old=c.title;c.title=title;if(persist()){render();toast('Title updated.')}else c.title=old;break}case'ask-delete':$('#delete-area').innerHTML='<div class="delete-confirm"><p>Delete this conversation from this device? This cannot be undone.</p>'+button('Delete conversation','delete','secondary danger')+button('Keep it','cancel-delete','tertiary')+'</div>';break;case'cancel-delete':render();break;case'delete':{const old=store.chats;store.chats=store.chats.filter(c=>c.id!==currentId);if(persist()){go('saved');toast('Conversation deleted.')}else store.chats=old;break}case'ask-clear':$('#delete-area').innerHTML='<div class="delete-confirm"><p>Delete all saved conversations from this device? This cannot be undone.</p>'+button('Delete all conversations','clear','secondary danger')+button('Cancel','cancel-delete','tertiary')+'</div>';break;case'clear':{const old=store.chats;store.chats=[];if(persist()){render();toast('Saved conversations deleted.')}else store.chats=old;break}case'motion':store.reduced=!store.reduced;persist();render();break;case'meditate':meditationReturn=activityReturn;seconds=180;medTotal=180;go('meditation');break;case'quick-meditate':meditationReturn=activityReturn;seconds=120;medTotal=120;go('meditation');break;case'play':toggleMeditation();break;case'game-start':showPattern();break}});
render();

document.addEventListener('keydown',e=>{if(e.key==='Escape'){const more=$('.room-more[open]');if(more){more.open=false;more.querySelector('summary').focus()}}});
$('#app').addEventListener('input',e=>{if(e.target.id==='music-volume'){const old=store.musicVolume;store.musicVolume=Number(e.target.value)/100;if(persist()){$('#volume-label').textContent=e.target.value+'%';window.ambientMusic?.sync()}else{store.musicVolume=old;e.target.value=Math.round((old??.6)*100)}}});

$('#app').addEventListener('change',async e=>{if(e.target.id!=='book-file')return;const file=e.target.files[0];if(!file)return;if(!/\.txt$/i.test(file.name)){toast('Choose a plain .txt file. PDF and EPUB are not supported.');e.target.value='';return}if(file.size>500*1024){toast('Choose a file smaller than 500 KB.');e.target.value='';return}try{const text=(await file.text()).replace(/\r\n?/g,'\n').trim();if(!text||text.includes('\0')){toast('This file does not contain readable plain text.');return}importDraft={title:file.name.replace(/\.txt$/i,''),text};go('import-book')}catch{toast('This file could not be read. Try another text file.')}});
const SAMPLE_READING=`The Lantern Keeper

At the edge of the village stood a lantern that nobody remembered lighting. Each evening its small circle of gold appeared on the stone path. Travelers paused beside it, loosened their bags, and looked up at the hill.

Mara had passed the lantern for years. One afternoon she decided to follow the path beyond it. She expected a house, perhaps a workshop. Instead, she found a cave with a wooden bench at its entrance and a kettle resting beside a cold fireplace.

A note on the bench said: “You may sit here. You do not have to explain why.”

She sat. The forest continued around her: a branch settling, a bird testing two notes, water finding its way between stones. Nothing waited for an answer.

After a while she noticed a box of small lanterns beneath the bench. Some were green, some blue, and one had a crooked handle. She chose the crooked one and carried it inside. The cave was not a single room but a collection of spaces, each with its own echo.

In the first room she found a table beneath a narrow opening to the sky. In the second, a pool reflected the ceiling like another world. The third contained nothing at all. Mara liked that room best. There was space to imagine what might belong there.

She placed her lantern on the floor and pictured a chair, a shelf, a window looking onto rain. She laughed at the idea of a window inside a hill. Then she decided that imagination did not have to ask the hill for permission.

When evening arrived, she returned the lantern to its box. Beside the first note she left another: “The empty room is still empty. I think that is part of what makes it lovely.”

Weeks later, she came back with a book. Someone had placed a cushion on the bench. The crooked lantern was still there. She took it into the empty room, opened her book, and began where she had stopped.

Outside, the village lantern glowed. It did not call anyone back. It simply made the path a little easier to find.

The end.`;

window.addEventListener("beforeunload",e=>{if(messages.length||draft.trim()||Object.values(noteDrafts).some(n=>n.text||n.title)||document.querySelector("#note-body")?.value.trim()){e.preventDefault();e.returnValue="";}});
